/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#0f172a',
        'surface-dim': '#051424',
        'on-tertiary-fixed': '#00210c',
        'surface-variant': '#273647',
        'inverse-primary': '#565e74',
        'background': '#051424',
        'on-surface': '#d4e4fa',
        'surface-container-high': '#1c2b3c',
        'surface-container-lowest': '#010f1f',
        'on-secondary-container': '#00515d',
        'on-primary': '#283044',
        'outline': '#909097',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-highest': '#273647',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#798098',
        'secondary': '#5de6ff',
        'error-container': '#93000a',
        'tertiary': '#4de082',
        'tertiary-fixed': '#6dfe9c',
        'tertiary-container': '#001d0a',
        'secondary-container': '#00cbe6',
        'surface': '#051424',
        'primary-fixed': '#dae2fd',
        'surface-tint': '#bec6e0',
        'inverse-on-surface': '#233143',
        'secondary-fixed-dim': '#2fd9f4',
        'tertiary-fixed-dim': '#4de082',
        'on-secondary': '#00363e',
        'on-tertiary-container': '#00954b',
        'error': '#ffb4ab',
        'on-surface-variant': '#c6c6cd',
        'on-primary-fixed': '#131b2e',
        'surface-bright': '#2c3a4c',
        'on-tertiary-fixed-variant': '#005227',
        'primary': '#bec6e0',
        'on-tertiary': '#003919',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container': '#122131',
        'on-secondary-fixed': '#001f25',
        'on-background': '#d4e4fa',
        'inverse-surface': '#d4e4fa',
        'secondary-fixed': '#a2eeff',
        'on-error': '#690005',
        'outline-variant': '#45464d',
        'surface-container-low': '#0d1c2d',
        'on-secondary-fixed-variant': '#004e5a',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'mono-code': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'base': '4px',
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
